
FROM ubuntu:22.04

# this is a non-interactive automated build - avoid some warning messages
ENV DEBIAN_FRONTEND noninteractive

# update dpkg repositories
RUN apt-get update

# install wget
RUN apt-get install -y wget

# set shell variables for java installation
ENV java_version 21
RUN ARCH=$(uname -m) && \
    if [ "$ARCH" = "x86_64" ]; then \
        filename="jdk-21_linux-x64_bin.tar.gz"; \
    elif [ "$ARCH" = "aarch64" ]; then \
        filename="jdk-21_linux-aarch64_bin.tar.gz"; \
    else \
        echo "Unsupported architecture: $ARCH" && exit 1; \
    fi && \
    downloadlink="https://download.oracle.com/java/21/latest/$filename" && \
    wget --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" -O /tmp/$filename $downloadlink && \
    mkdir /opt/java-oracle/ && mkdir /opt/java-oracle/jdk21/ && tar -zxf /tmp/$filename -C /opt/java-oracle/jdk21/ --strip-components 1
ENV JAVA_HOME /opt/java-oracle/jdk21
ENV PATH $JAVA_HOME/bin:$PATH

# configure symbolic links for the java and javac executables
RUN update-alternatives --install /usr/bin/java java $JAVA_HOME/bin/java 20000 && update-alternatives --install /usr/bin/javac javac $JAVA_HOME/bin/javac 20000

ARG JAR_FILE
ENV JVM_OPTS=""

RUN groupadd -r -g 2020 pantera && \
    useradd -M -r -g pantera -u 2021 -s /sbin/nologin pantera && \
    mkdir -p /etc/pantera /usr/lib/pantera /var/pantera && \
    chown pantera:pantera -R /etc/pantera /usr/lib/pantera /var/pantera
USER 2021:2020

COPY target/dependency  /usr/lib/pantera/lib
COPY target/${JAR_FILE} /usr/lib/pantera/pantera.jar
COPY src/test/resources/ssl/keystore.jks /var/pantera/keystore.jks

VOLUME /var/pantera /etc/pantera
WORKDIR /var/pantera
EXPOSE 8080 8086 8091
CMD [ "sh", "-c", "java $JVM_ARGS --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.security=ALL-UNNAMED -cp /usr/lib/pantera/pantera.jar:/usr/lib/pantera/lib/* com.artipie.VertxMain --config-file=/etc/pantera/pantera.yml --port=8080 --api-port=8086" ]
