
#!/bin/sh

set -eu

# Usage function
usage() {
    echo "Usage: $0 <root-directory> [groupId]"
    echo "  Generates .pom files and checksums (md5, sha1, sha256, sha512) for YAML files"
    echo "  in Maven-structured directories (groupId/artifactId/version)"
    echo ""
    echo "Arguments:"
    echo "  root-directory  Root directory to scan for artifacts"
    echo "  groupId         (Optional) Only process artifacts starting with this groupId"
    exit 1
}

# Check arguments
if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    usage
fi

ROOT_DIR="$1"
GROUP_ID_FILTER="${2:-}"

if [ ! -d "$ROOT_DIR" ]; then
    echo "Error: Directory '$ROOT_DIR' does not exist"
    exit 1
fi

# Output files
SKIPPED_DIRS_FILE="${ROOT_DIR}/skipped-directories.txt"
CREATED_FILES_FILE="${ROOT_DIR}/created-files.txt"
PROCESSED_DIRS_FILE="${ROOT_DIR}/.processed-dirs.tmp"

# Clear output files if they exist
> "$SKIPPED_DIRS_FILE"
> "$CREATED_FILES_FILE"
> "$PROCESSED_DIRS_FILE"

# Function to generate POM content
generate_pom() {



    group_id="$1"
    artifact_id="$2"
    version="$3"
    
    cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>$group_id</groupId>
    <artifactId>$artifact_id</artifactId>
    <version>$version</version>
    <packaging>yaml</packaging>
</project>
EOF
}

# Function to check if any checksums exist for a file
checksum_files_exist() {



    file="$1"
    base_name="${file%.yaml}"
    extension="${file##*.}"
    
    if [ "$extension" = "yaml" ]; then
        base_name="${file%.yaml}"
    else
        base_name="$file"
    fi
    
    [ -f "${base_name}.${extension}.md5" ] || \
    [ -f "${base_name}.${extension}.sha1" ] || \
    [ -f "${base_name}.${extension}.sha256" ] || \
    [ -f "${base_name}.${extension}.sha512" ]
}

# Function to check if directory contains only YAML files
check_directory_has_only_yaml() {


    dir="$1"
    has_non_yaml=0
    
    # Find all files in directory (non-recursive)
    find "$dir" -maxdepth 1 -type f | while IFS= read -r file; do

        basename_file=$(basename "$file")
        # Skip if it's a checksum file or pom file (generated by this script)
        case "$basename_file" in
            *.md5|*.sha1|*.sha256|*.sha512|*.pom)
                continue
                ;;
        esac
        # Check if it's not a yaml file
        case "$basename_file" in
            *.yaml|*.yml)
                # It's a yaml file, continue
                ;;
            *)
                # Not a yaml file
                return 1
                ;;
        esac
    done
    
    return 0
}

# Function to generate checksums for a file
generate_checksums() {



    file="$1"
    extension="${file##*.}"
    base_name="${file%.*}"
    
    echo "  Generating checksums for: $(basename "$file")"
    
    # MD5

    if command -v md5sum >/dev/null 2>&1; then
        md5sum "$file" | awk '{print $1}' > "${base_name}.${extension}.md5"
        echo "${base_name}.${extension}.md5" >> "$CREATED_FILES_FILE"

    elif command -v md5 >/dev/null 2>&1; then
        md5 -q "$file" > "${base_name}.${extension}.md5"
        echo "${base_name}.${extension}.md5" >> "$CREATED_FILES_FILE"
    else
        echo "    Warning: md5 tool not found"
    fi
    
    # SHA1

    if command -v sha1sum >/dev/null 2>&1; then
        sha1sum "$file" | awk '{print $1}' > "${base_name}.${extension}.sha1"
        echo "${base_name}.${extension}.sha1" >> "$CREATED_FILES_FILE"

    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 1 "$file" | awk '{print $1}' > "${base_name}.${extension}.sha1"
        echo "${base_name}.${extension}.sha1" >> "$CREATED_FILES_FILE"
    else
        echo "    Warning: sha1 tool not found"
    fi
    
    # SHA256
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$file" | awk '{print $1}' > "${base_name}.${extension}.sha256"
        echo "${base_name}.${extension}.sha256" >> "$CREATED_FILES_FILE"
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$file" | awk '{print $1}' > "${base_name}.${extension}.sha256"
        echo "${base_name}.${extension}.sha256" >> "$CREATED_FILES_FILE"
    else
        echo "    Warning: sha256 tool not found"
    fi
    
    # SHA512
    if command -v sha512sum >/dev/null 2>&1; then
        sha512sum "$file" | awk '{print $1}' > "${base_name}.${extension}.sha512"
        echo "${base_name}.${extension}.sha512" >> "$CREATED_FILES_FILE"
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 512 "$file" | awk '{print $1}' > "${base_name}.${extension}.sha512"
        echo "${base_name}.${extension}.sha512" >> "$CREATED_FILES_FILE"
    else
        echo "    Warning: sha512 tool not found"
    fi
}

# Counters file for cross-subshell communication
COUNTERS_FILE="${ROOT_DIR}/.counters.tmp"
echo "0 0 0" > "$COUNTERS_FILE"

# Find all YAML files in version directories
# Expected structure: groupId/artifactId/version/*.yaml
if [ -n "$GROUP_ID_FILTER" ]; then
    echo "Scanning $ROOT_DIR for Maven-structured directories with groupId: $GROUP_ID_FILTER..."
else
    echo "Scanning $ROOT_DIR for Maven-structured directories..."
fi

# Use find to locate all yaml files, then process their parent directories
find "$ROOT_DIR" -type f -name "*.yaml" | while IFS= read -r yaml_file; do
    # Read current counters
    read processed skipped skipped_non_yaml < "$COUNTERS_FILE"
    # Get the directory containing the YAML file (version dir)
    version_dir=$(dirname "$yaml_file")
    version=$(basename "$version_dir")
    
    # Skip if we already processed or skipped this directory
    if grep -Fxq "$version_dir" "$PROCESSED_DIRS_FILE" 2>/dev/null; then
        continue
    fi
    
    # Get artifact directory
    artifact_dir=$(dirname "$version_dir")
    artifact_id=$(basename "$artifact_dir")
    
    # Get group directory (may have multiple levels with dots)
    group_dir=$(dirname "$artifact_dir")
    
    # Calculate group_id by removing ROOT_DIR prefix and converting path to dots
    group_path="${group_dir#$ROOT_DIR}"
    group_path="${group_path#/}"  # Remove leading slash if present
    
    # Convert path separators to dots for groupId
    group_id=$(echo "$group_path" | tr '/' '.')
    
    # Skip if group_id is empty (file is too close to root)
    if [ -z "$group_id" ] || [ -z "$artifact_id" ] || [ -z "$version" ]; then
        echo "Skipping: $yaml_file (invalid Maven structure)"
        echo "$version_dir" >> "$PROCESSED_DIRS_FILE"
        echo "$processed $skipped $skipped_non_yaml" > "$COUNTERS_FILE"
        continue
    fi
    
    # Skip if groupId filter is set and this artifact doesn't match
    if [ -n "$GROUP_ID_FILTER" ]; then
        case "$group_id" in
            "$GROUP_ID_FILTER"*)
                # Match - continue processing
                ;;
            *)
                # No match - skip
                echo "$version_dir" >> "$PROCESSED_DIRS_FILE"
                echo "$processed $skipped $skipped_non_yaml" > "$COUNTERS_FILE"
                continue
                ;;
        esac
    fi
    
    # Check if directory contains only YAML files
    if ! check_directory_has_only_yaml "$version_dir"; then
        echo "Skipping: $group_id:$artifact_id:$version (contains non-YAML files)"
        echo "$version_dir" >> "$SKIPPED_DIRS_FILE"
        echo "$version_dir" >> "$PROCESSED_DIRS_FILE"
        skipped_non_yaml=$((skipped_non_yaml + 1))
        echo "$processed $skipped $skipped_non_yaml" > "$COUNTERS_FILE"
        echo ""
        continue
    fi
    
    pom_file="${version_dir}/${artifact_id}-${version}.pom"
    
    # Check what needs to be generated
    yaml_checksums_exist=$(checksum_files_exist "$yaml_file" && echo "yes" || echo "no")
    pom_exists=$([ -f "$pom_file" ] && echo "yes" || echo "no")
    pom_checksums_exist=$(checksum_files_exist "$pom_file" && echo "yes" || echo "no")
    
    # Skip if everything already exists
    if [ "$pom_exists" = "yes" ] && [ "$yaml_checksums_exist" = "yes" ] && [ "$pom_checksums_exist" = "yes" ]; then
        echo "Skipping: $group_id:$artifact_id:$version (all files already exist)"
        echo "$version_dir" >> "$PROCESSED_DIRS_FILE"
        skipped=$((skipped + 1))
        echo "$processed $skipped $skipped_non_yaml" > "$COUNTERS_FILE"
        echo ""
        continue
    fi
    
    echo "Processing: $group_id:$artifact_id:$version"
    echo "  YAML: $(basename "$yaml_file")"
    
    # Generate POM file if it doesn't exist
    if [ "$pom_exists" = "no" ]; then
        generate_pom "$group_id" "$artifact_id" "$version" > "$pom_file"
        echo "$pom_file" >> "$CREATED_FILES_FILE"
        echo "  Created: $(basename "$pom_file")"
    else
        echo "  POM already exists: $(basename "$pom_file")"
    fi
    
    # Generate checksums for the YAML file if they don't exist
    if [ "$yaml_checksums_exist" = "no" ]; then
        generate_checksums "$yaml_file"
    else
        echo "  YAML checksums already exist"
    fi
    
    # Generate checksums for the POM file if they don't exist
    if [ "$pom_checksums_exist" = "no" ]; then
        generate_checksums "$pom_file"
    else
        echo "  POM checksums already exist"
    fi
    
    echo "$version_dir" >> "$PROCESSED_DIRS_FILE"
    processed=$((processed + 1))
    echo "$processed $skipped $skipped_non_yaml" > "$COUNTERS_FILE"
    echo ""
done

# Read final counters
read processed skipped skipped_non_yaml < "$COUNTERS_FILE"

# Clean up temporary files
rm -f "$PROCESSED_DIRS_FILE" "$COUNTERS_FILE"

echo ""
echo "Done! Processed $processed artifact(s), skipped $skipped artifact(s) (already exists)"
echo "Skipped $skipped_non_yaml artifact(s) (contains non-YAML files)"
echo ""
echo "Reports:"
echo "  - Created files: $CREATED_FILES_FILE"
echo "  - Skipped directories: $SKIPPED_DIRS_FILE"
