"""
Smoke tests for Pantera's PEP 691 JSON Simple API.

These run AFTER `uv sync` has installed the resolved packages into
the venv. The tests verify that the packages actually installed and
are importable — proving that:
  1. The PEP 691 JSON index was valid (uv parsed it)
  2. The download URLs in the JSON resolved correctly (uv fetched them)
  3. The hosted + proxied group routing worked (all packages found)

Run:
    uv run python -m pytest tests/ -v
"""
import importlib
import json
import subprocess
import sys


def test_requests_installed():
    """requests is a proxied package — verifies proxy JSON index works."""
    import requests
    assert hasattr(requests, "get"), "requests.get must be callable"
    resp = requests.get("https://httpbin.org/status/200", timeout=5)
    assert resp.status_code == 200


def test_hello_installed():
    """hello is a hosted package — verifies hosted JSON index + relative URLs."""
    hello = importlib.import_module("hello")
    assert hasattr(hello, "__version__") or True, "hello package must be importable"


def test_pydantic_installed():
    """pydantic exercises deep transitive resolution via the JSON API."""
    import pydantic
    assert pydantic.VERSION, "pydantic must expose a VERSION"


def test_uv_lockfile_exists():
    """uv.lock must exist after a successful `uv lock`."""
    from pathlib import Path
    lock = Path(__file__).parent.parent / "uv.lock"
    assert lock.exists(), "uv.lock must be generated by `uv lock`"


def test_uv_lock_check_passes():
    """
    `uv lock --check` verifies the lockfile is consistent with
    pyproject.toml. If PEP 691 responses changed between lock and
    check (e.g., stale cache served different versions), this fails.
    """
    result = subprocess.run(
        [sys.executable, "-m", "uv", "lock", "--check"],
        capture_output=True,
        text=True,
        cwd=str(__import__("pathlib").Path(__file__).parent.parent),
    )
    # uv lock --check may not be available in all uv versions;
    # skip gracefully if the subcommand isn't recognized.
    if "unrecognized" in result.stderr.lower():
        import pytest
        pytest.skip("uv lock --check not available in this uv version")
    assert result.returncode == 0, (
        f"uv lock --check failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
    )


def test_json_index_is_valid_pep691():
    """
    Fetch the JSON simple index for 'hello' directly from Pantera
    and validate its PEP 691 structure. This is a direct HTTP-level
    test independent of uv — it catches regressions even if uv
    falls back to HTML silently.
    """
    import requests as req

    index_url = (
        "http://ayd:ayd@localhost:8081"
        "/test_prefix/api/pypi/pypi_group/simple/hello/"
    )
    resp = req.get(
        index_url,
        headers={"Accept": "application/vnd.pypi.simple.v1+json"},
        timeout=10,
    )
    assert resp.status_code == 200, f"Expected 200, got {resp.status_code}"

    ctype = resp.headers.get("Content-Type", "")
    assert "application/vnd.pypi.simple.v1+json" in ctype, (
        f"Content-Type must be PEP 691 JSON, got: {ctype}"
    )

    data = resp.json()
    assert "meta" in data, "PEP 691 response must have a 'meta' key"
    assert data["meta"].get("api-version") == "1.1", (
        f"api-version must be 1.1, got: {data['meta'].get('api-version')}"
    )
    assert data.get("name") == "hello", (
        f"package name must be 'hello', got: {data.get('name')}"
    )
    assert len(data.get("files", [])) > 0, "files array must not be empty"

    for f in data["files"]:
        # URL must be relative (no protocol-relative //pkg/... or absolute http://...)
        url = f.get("url", "")
        assert not url.startswith("//"), (
            f"URL must not be protocol-relative: {url}"
        )
        assert not url.startswith("http"), (
            f"URL should be relative per PEP 691 recommendation: {url}"
        )
        # Must have a sha256 hash
        assert "sha256" in f.get("hashes", {}), (
            f"Each file must have a sha256 hash: {f.get('filename')}"
        )
        # yanked must be false (boolean) or a string (reason), never true (boolean)
        yanked = f.get("yanked")
        assert yanked is False or isinstance(yanked, str), (
            f"yanked must be false or a string, got: {type(yanked).__name__} = {yanked}"
        )
