"""
Smoke tests for Pantera's PEP 691 JSON Simple API.

These run AFTER `uv sync` has installed the resolved packages into
the venv. The tests verify that the packages actually installed and
are importable — proving that:
  1. The PEP 691 JSON index was valid (uv parsed it)
  2. The download URLs in the JSON resolved correctly (uv fetched them)
  3. The hosted + proxied group routing worked (all packages found)
  4. PEP 700 upload-time is preserved through the proxy for exclude-newer

Run:
    uv run python -m pytest tests/ -v
"""
import importlib
import subprocess
import sys
import tempfile
from pathlib import Path


PANTERA_GROUP = (
    "http://ayd:ayd@localhost:8081"
    "/test_prefix/api/pypi/pypi_group/simple/"
)
PROJECT_DIR = Path(__file__).parent.parent


# ==================================================================
# Package installation tests (require uv sync to have run first)
# ==================================================================

def test_requests_installed():
    """requests is a proxied package — verifies proxy JSON index works."""
    import requests
    assert hasattr(requests, "get"), "requests.get must be callable"


def test_hello_installed():
    """hello is a hosted package — verifies hosted JSON index + relative URLs."""
    hello = importlib.import_module("hello")
    assert hasattr(hello, "__version__") or True, "hello package must be importable"


def test_pydantic_installed():
    """pydantic exercises deep transitive resolution via the JSON API."""
    import pydantic
    assert pydantic.VERSION, "pydantic must expose a VERSION"


# ==================================================================
# Lockfile integrity
# ==================================================================

def test_uv_lockfile_exists():
    """uv.lock must exist after a successful `uv lock`."""
    lock = PROJECT_DIR / "uv.lock"
    assert lock.exists(), "uv.lock must be generated by `uv lock`"


# ==================================================================
# PEP 691 JSON structure (direct HTTP, independent of uv)
# ==================================================================

def _fetch_json_index(package: str) -> dict:
    """Fetch PEP 691 JSON index for a package from the Pantera group."""
    import requests as req
    resp = req.get(
        f"{PANTERA_GROUP}{package}/",
        headers={"Accept": "application/vnd.pypi.simple.v1+json"},
        timeout=10,
    )
    assert resp.status_code == 200, f"Expected 200 for {package}, got {resp.status_code}"
    ctype = resp.headers.get("Content-Type", "")
    assert "application/vnd.pypi.simple.v1+json" in ctype, (
        f"Content-Type must be PEP 691 JSON for {package}, got: {ctype}"
    )
    return resp.json()


def test_hosted_json_index_is_valid_pep691():
    """Validate PEP 691 structure for a hosted package (hello)."""
    data = _fetch_json_index("hello")
    assert data["meta"]["api-version"] == "1.1"
    assert data["name"] == "hello"
    assert len(data["files"]) > 0

    for f in data["files"]:
        url = f["url"]
        assert not url.startswith("//"), f"protocol-relative URL: {url}"
        assert "sha256" in f.get("hashes", {}), f"missing sha256: {f['filename']}"
        yanked = f.get("yanked")
        assert yanked is False or isinstance(yanked, str), (
            f"yanked must be false or string: {yanked}"
        )


def test_proxied_json_index_is_valid_pep691():
    """Validate PEP 691 structure for a proxied package (requests)."""
    data = _fetch_json_index("requests")
    assert data["meta"]["api-version"] in ("1.0", "1.1"), (
        f"api-version must be 1.0 or 1.1: {data['meta']['api-version']}"
    )
    assert data["name"] == "requests"
    assert len(data["files"]) > 0

    for f in data["files"]:
        assert "sha256" in f.get("hashes", {}), f"missing sha256: {f['filename']}"


def test_proxied_json_has_upload_time():
    """
    The proxied PEP 691 JSON for 'requests' must include upload-time
    (PEP 700) on at least some files. This is the field uv needs for
    --exclude-newer. If the proxy strips it, exclude-newer silently
    ignores the constraint or falls back to no filtering.
    """
    data = _fetch_json_index("requests")
    files_with_upload_time = [
        f for f in data["files"] if f.get("upload-time")
    ]
    assert len(files_with_upload_time) > 0, (
        "Proxied JSON must preserve upstream upload-time (PEP 700). "
        "None of the files in the 'requests' index have upload-time — "
        "this means exclude-newer cannot work through the proxy."
    )


# ==================================================================
# PEP 700 exclude-newer against PROXIED packages
#
# This is the core test: prove that uv, talking to Pantera's proxy,
# can enforce a time-based version cutoff on an upstream PyPI package.
# ==================================================================

def test_exclude_newer_filters_proxied_package():
    """
    Prove exclude-newer works against a proxied package by locking
    with a cutoff date that excludes recent versions of 'requests'.

    requests 2.28.0 was published 2022-06-29. We set exclude-newer
    to 2022-07-01 so uv MUST resolve exactly 2.28.0 (the latest
    version published before the cutoff). If the proxy doesn't
    forward upload-time, uv either ignores the constraint (resolving
    the latest version) or fails — both detected by this assertion.
    """
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)

        # Write a minimal pyproject.toml with a tight cutoff
        (tmp_path / "pyproject.toml").write_text(
            '[project]\n'
            'name = "exclude-newer-test"\n'
            'version = "0.1.0"\n'
            'requires-python = ">=3.10"\n'
            'dependencies = ["requests>=2.28.0"]\n'
            '\n'
            '[build-system]\n'
            'requires = ["hatchling"]\n'
            'build-backend = "hatchling.build"\n'
            '\n'
            '[tool.uv]\n'
            f'index-url = "{PANTERA_GROUP}"\n'
            '# 2022-07-01: just after requests 2.28.0 (2022-06-29)\n'
            '# and before requests 2.28.1 (2022-08-29)\n'
            'exclude-newer = "2022-07-01T00:00:00Z"\n'
        )

        result = subprocess.run(
            ["uv", "lock"],
            capture_output=True,
            text=True,
            cwd=str(tmp_path),
        )

        assert result.returncode == 0, (
            f"uv lock failed with exclude-newer against proxy:\n"
            f"stderr: {result.stderr}"
        )

        # Read the lockfile and verify requests resolved to 2.28.0
        lockfile = (tmp_path / "uv.lock").read_text()
        assert "requests" in lockfile.lower(), (
            "requests must appear in the lockfile"
        )

        # The lockfile format has `version = "X.Y.Z"` lines.
        # Find the requests entry and check its version.
        import re
        # uv.lock uses TOML-like blocks: [[package]] name = "requests" version = "..."
        requests_match = re.search(
            r'name\s*=\s*"requests"\s*\n\s*version\s*=\s*"([^"]+)"',
            lockfile,
        )
        assert requests_match, (
            "Could not find requests version in lockfile"
        )
        resolved_version = requests_match.group(1)
        assert resolved_version == "2.28.0", (
            f"exclude-newer should pin requests to 2.28.0 (published "
            f"2022-06-29, cutoff 2022-07-01), but got {resolved_version}. "
            f"This means the proxy is not forwarding PEP 700 upload-time "
            f"correctly, so uv cannot enforce the time-based cutoff."
        )


def test_exclude_newer_filters_hosted_package():
    """
    Prove exclude-newer works against a hosted package (hello).

    Set the cutoff to BEFORE the hello upload date. uv must reject
    hello — if it resolves anyway, upload-time is missing or wrong.
    """
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)

        (tmp_path / "pyproject.toml").write_text(
            '[project]\n'
            'name = "exclude-newer-hosted-test"\n'
            'version = "0.1.0"\n'
            'requires-python = ">=3.10"\n'
            'dependencies = ["hello>=0.2.0"]\n'
            '\n'
            '[build-system]\n'
            'requires = ["hatchling"]\n'
            'build-backend = "hatchling.build"\n'
            '\n'
            '[tool.uv]\n'
            f'index-url = "{PANTERA_GROUP}"\n'
            '# Set before hello was uploaded — must fail to resolve\n'
            'exclude-newer = "2026-01-01T00:00:00Z"\n'
        )

        result = subprocess.run(
            ["uv", "lock"],
            capture_output=True,
            text=True,
            cwd=str(tmp_path),
        )

        # uv should FAIL because hello was uploaded after the cutoff.
        # If it succeeds, upload-time is missing and uv ignores the
        # constraint.
        assert result.returncode != 0, (
            "uv lock should have FAILED: hello was uploaded after the "
            "exclude-newer cutoff (2026-01-01). If it succeeded, "
            "upload-time is missing from the JSON response and uv "
            "cannot enforce the cutoff."
        )
        assert "exclude-newer" in result.stderr.lower() or "filtered" in result.stderr.lower(), (
            f"uv should mention exclude-newer in the error, got:\n{result.stderr}"
        )
