version: "3.9"
services:
  artipie:
    depends_on:
      artipie-db:
        condition: service_healthy
      keycloak:
        condition: service_started
    image: auto1-artipie:1.18.15
    container_name: artipie
    restart: unless-stopped
    environment:
      - ARTIPIE_USER_NAME=artipie
      - ARTIPIE_USER_PASS=artipie
      - ARTIPIE_CONFIG=/etc/artipie/artipie.yml
      - HOME=/home/
      - AWS_CONFIG_FILE=/home/.aws/config
      - AWS_SHARED_CREDENTIALS_FILE=/home/.aws/credentials
      - AWS_SDK_LOAD_CONFIG=1
      - AWS_PROFILE=shared-services-qa-devops
      - AWS_REGION=eu-west-1
      # Version (change this when bumping version)
      - ARTIPIE_VERSION=1.18.15
      # Log4j2 configuration file location
      - LOG4J_CONFIGURATION_FILE=/etc/artipie/log4j2.xml
    volumes:
      - ./artipie/artipie.yml:/etc/artipie/artipie.yml
      - ./log4j2.xml:/etc/artipie/log4j2.xml
      - ./artipie/repo:/var/artipie/repo
      - ./artipie/security:/var/artipie/security
      - ./artipie/data:/var/artipie/data
      - ./artipie/cache:/var/artipie/cache
      - ~/.aws:/home/.aws
    networks:
      - artipie-net
    ports:
      - "8086:8086"
      - "8087:8087"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - artipie
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - artipie-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    depends_on:
      artipie-db:
        condition: service_healthy
    command:
    - start-dev
    - --import-realm
    restart: unless-stopped
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://artipie-db:5432/keycloak
      - KC_DB_USERNAME=artipie
      - KC_DB_PASSWORD=artipie
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
    ports:
      - "8080:8080"
    volumes:
    - ./keycloak-export:/opt/keycloak/data/import
    networks:
      - artipie-net

  front:
    depends_on:
      - artipie
    image: artipie/front:latest
    container_name: front
    restart: unless-stopped
    networks:
      - artipie-net
    environment:
      - ARTIPIE_REST=http://artipie:8086
    ports:
      - "8082:8080"

  artipie-db:
    image: postgres:15-alpine
    container_name: artipie-db
    restart: unless-stopped
    networks:
      - artipie-net
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=artipie
      - POSTGRES_PASSWORD=artipie
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "artifacts" ]
      interval: 10s
      timeout: 60s
      retries: 6

networks:
  artipie-net:
    driver: bridge